import type { Metadata } from 'next';
import './globals.css';
import { cn } from '@/lib/utils';
import { Toaster } from '@/components/ui/toaster';
import ClientSideProvider from '@/firebase/client-side-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased'
        )}
      >
        <ClientSideProvider>
          {children}
          <Toaster />
        </ClientSideProvider>
      </body>
    </html>
  );
}
